// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgbicgatmyeaxbdsmfwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnYmljZ2F0bXllYXhiZHNtZnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTMzODAsImV4cCI6MjA2MTEyOTM4MH0.Uw0UgylHfKFwLbng-PgK9eHNdy8yAtwlwcMR8UrzZgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);